- hosts: all
  sudo: yes

  pre_tasks:
    - name: Install dependencies
      yum: "name={{ item }} state=installed"
      with_items:
        - libselinux-python
        - unzip

  vars:
    GOCD_ADMIN_EMAIL: jenscobie@gmail.com

  roles:
      - { role: tpbrown.gocd, tags: [ 'agent' ] }

  tasks:
    - { include: tasks/main.yml }

